
image: php:8.2
#  name: berkay18/quiz
#  username: $DOCKER_HUB_berkay18
#  password: $DOCKER_HUB_Stage1999!
#  email: berkay@meijdenmedia.nl


pipelines:
  default:
    - step:
        name: "Setup project"
        script:
          - apt-get update && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev git zip
          - docker-php-ext-install pdo_mysql
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - cp .env.pipelines .env
          - export COMPOSER_ALLOW_SUPERUSER=1
          - composer install
          - php artisan key:generate
          - php artisan migrate --force
          - ./vendor/bin/pest
          - ./vendor/bin/phpstan analyse
        services:
            - mysql

definitions:
  services:
    mysql:
      image: mysql:8.0
      variables:
        MYSQL_DATABASE: quiz
        MYSQL_ROOT_PASSWORD: password123!